### ISSUE TITLE
violin plot shuffles categorical keys

### ISSUE THREAD

**Issue by gokceneraslan** [klarman-cell-observatory/scPlot#4]
Categorical types get mixed up in violin plots. It's also visible in the notebook:

![image](https://user-images.githubusercontent.com/1140359/68916772-6fe28a00-0735-11ea-9e36-063cd6526c80.png)

It doesn't happen in composition plots. I suspect it's because violin calls `__fix_color_by_data_type` and composition does not. Conversion to string in `__fix_color_by_data_type` might lead to the mixing.

This is also related to the PR #3 . I think if you outsource color assignment to scanpy, everything will be easier and cleaner on the scplot side.

**Comment by gokceneraslan** [comment]
Wow, wait this is a more serious bug than I thought. I initially thought it's only the order that is mixed up, however it seems like the color is correct but the labels are just shuffled. 

Just compare colors and orders in the following plots:

![image](https://user-images.githubusercontent.com/1140359/68916997-555ce080-0736-11ea-8d46-9d861fe9c700.png)

**Comment by gokceneraslan** [comment]
heatmap has a similar problem, labels are not shuffled but just not in correct order.

![image](https://user-images.githubusercontent.com/1140359/68917389-057f1900-0738-11ea-87d6-b4e0e630cf5e.png)

**Comment by bli25** [comment]
@gokceneraslan , thanks a lot for reporting this! We also noticed this bug (@joshua-gould) and fixing it is in our todo list.

Thanks,
Bo

**Comment by joshua-gould** [comment]
Sort order and colors are now fixed. Plots will use colors in adata.uns if available. Additionally, scanpy colors will be created if scanpy is installed using canpy.plotting._utils.add_colors_for_categorical_sample_annotation.
